mature:
	go run main.go -accounts=1000000 -validators=10000 -delegators=10000 -password=mysecurepass -multiNode=false -concurrency=100 -buffer=1000
full:
	go run main.go -accounts=10000000 -validators=100000 -delegators=100000 -password=mysecurepass -multiNode=false -concurrency=2  -buffer=500
max:
	go run main.go -accounts=100000000 -validators=1000000 -delegators=1000000 -password=mysecurepass -multiNode=false -concurrency=100 -buffer=1000
